version: '3.8'

services:
  cleango:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./data:/app/data
    environment:
      - DATABASE_PATH=/app/data/cleango.db
    restart: unless-stopped
